sudo: required
dist: trusty
language: node_js
node_js:
- '9'
install:
- npm install
script:
#- npm run lint
#- npm run test
- npm run build
after_success:
- ./lighthouse_test.sh
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "repnet-963ae"